#!/bin/bash
echo "🚀 Building the application..."
npm run build

echo ""
echo "✅ Build complete! Your site is ready in the 'dist' folder."
echo ""
echo "📦 To deploy your site, you have several options:"
echo ""
echo "1️⃣  Netlify Drop (Easiest - No CLI needed):"
echo "   → Go to https://app.netlify.com/drop"
echo "   → Drag and drop the 'dist' folder"
echo "   → Your site will be live instantly!"
echo ""
echo "2️⃣  Netlify CLI:"
echo "   → Run: npx netlify-cli deploy --prod --dir=dist"
echo ""
echo "3️⃣  Vercel:"
echo "   → Run: npx vercel --prod"
echo ""
echo "4️⃣  GitHub Pages:"
echo "   → Run: npx gh-pages -d dist"
echo ""
echo "📝 Don't forget to set environment variables:"
echo "   VITE_SUPABASE_URL=https://0ec90b57d6e95fcbda19832f.supabase.co"
echo "   VITE_SUPABASE_ANON_KEY=<your-key>"
echo ""
